import React from 'react'
import './Privacy.css';

function Privacy() {
  return (
    <div>
      <div className='term-intro'>
        <div className='term-text'>
          <h2>SmartWave Privacy Policy</h2>
          <p>This privacy policy describes SmartWave's policies and procedures for the collection, use, and disclosure of your information when you respond to our advertisements and tells you about your privacy rights and how the law protects you. We use your personal data to contact and support you, as well as to provide and improve the service. By using the service, you agree to the collection and use of information in accordance with this privacy policy.</p>
        </div>

        <div className='term-img'>
          <img src="https://res.cloudinary.com/dxnukbo0u/image/upload/v1706573577/woman-holding-padlock-laptop_x329r0.jpg" alt="" /> 
        </div>
      </div>

      <div className='refund'>
        <span>Interpretation and Definitions</span>

        <p><strong>Interpretation:</strong>The words in which the initial letter is capitalized have meanings defined under the following conditions: The following definitions shall have the same meaning regardless of whether they appear in the singular or plural.</p>

        <p><strong>Definitions:</strong> For the purposes of this privacy policy: <br></br></p>

        <div className='pad-list'>
          <div>
            <div className='dot'></div>
            <p><strong>Company:</strong> (referred to as either the company, we, us, or our in this agreement) refers to SmartWave.</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>Device:</strong> means any device that can access the service, such as a computer, a cellphone, or a digital tablet.</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>Personal data:</strong> is any information that relates to an identified or identifiable individual.</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>Service:</strong> refers to the advertisement, website, or application.</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>Service provider:</strong> means any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, provide the service on behalf of the company, perform services related to the service, or assist the company in analyzing how the service is used.</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>Usage data:</strong> refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</p>
          </div>
          <div>
            <div className='dot'></div>
            <p><strong>You:</strong> means the individual accessing or using the service, or the company or other legal entity on behalf of which such an individual is accessing or using the service, as applicable.</p>
          </div>
        </div>

        <span>Collecting and using your personal data</span>
        <span>Types of data collected</span>

        <p><strong>Personal Data:</strong> While using our service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>

         <div className='pad-list'>
           <div>
            <div className='dot'></div>
            <p>First name and last name</p>
            </div>

           <div>
           <div className='dot'></div>
            <p>Email address</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>Phone number</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>Location details such as your address, city, or country</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>Any other data, such as personal preferences, requirements, or comments</p>
           </div>
         </div>

         <p><strong>Use of Your Personal Data:</strong> SmartWave may use personal data for the following purposes:</p>

         <div className='pad-list'>
           <div>
            <div className='dot'></div>
             <p>To provide and maintain our service, including monitoring the usage of our service.</p>
            </div>

           <div>
           <div className='dot'></div>
            <p>To manage your account: manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user.</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased, or of any other contract with Us through the Service.</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>To contact you: to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
            </div>
           <div>
            <div className='dot'></div>
            <p>To provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or inquired about, unless you have opted not to receive such information.</p>
           </div>
           <div>
            <div className='dot'></div>
            <p>To manage your requests: To attend to and manage your requests for us.</p>
           </div>
           <div>
            <div className='dot'></div>
            <p>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
           </div>
           <div>
            <div className='dot'></div>
            <p>For other purposes: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our service, products, services, marketing, and your experience.</p>
           </div>
         </div>

         <span>Sharing of Your Personal Data:</span>

         <p>We may share your personal information in the following situations:</p>

         
         <div className='pad-list'>
           <div>
            <div className='dot'></div>
             <p>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our service and to contact You.</p>
            </div>

           <div>
           <div className='dot'></div>
            <p>For business transfers: We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business by another company.</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>With Affiliates: We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.</p>
           </div>
           <div>
           <div className='dot'></div>
            <p>With business partners: We may share your information with our business partners to offer you certain products, services, or promotions.</p>
            </div>
           <div>
            <div className='dot'></div>
            <p>With other users: when you share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed.</p>
           </div>
           <div>
            <div className='dot'></div>
            <p>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</p>
           </div>       
         </div>

         <span>Retention of Your Personal Data:</span>
         <p>SmartWave will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. SmartWave will also retain usage data for internal analysis purposes.</p>

        <span>Transfer of Your Personal Data:</span>
        <p>Your information, including personal data, is processed at the operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
        <p>SmartWave will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

        <span>Disclosure of Your Personal Data</span>

        <p><strong>Law enforcement:</strong> Under certain circumstances, SmartWave may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
        <p><strong>Other legal requirements:</strong> SmartWave may disclose your personal data in the good faith belief that such action is necessary to:</p>

        <div className='pad-list'>
             <div>
              <div className='dot'></div>
              <p>Comply with a legal obligation</p>
             </div>

            <div>
             <div className='dot'></div>
              <p>Protect and defend the rights or property of the company.</p>
             </div>

             <div>
              <div className='dot'></div>
              <p>Prevent or investigate possible wrongdoing in connection with the service.</p>
             </div>

            <div>
             <div className='dot'></div>
              <p>Protect the personal safety of users of the service or the public.</p>
             </div>

            <div>
             <div className='dot'></div>
              <p>Protect against legal liability.</p>
             </div>
          </div>

          <p>Security of your personal data. The security of your personal data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security. Links to Other Websites. Our service may contain links to other websites that are not operated by us.</p>
          <p>If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the privacy policies of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
          <p>Changes to this Privacy Policy. We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page. You are advised to review this privacy policy periodically for any changes. Changes to this privacy policy are effective when they are posted on this page. This privacy policy was last updated on 2024. Jan 28, 20:58:18.</p>
          <p>Contact Us If you have any questions about this privacy policy, you can contact us via email at support@smartwave.ng.</p>

      </div>       
    </div>
  )
}

export default Privacy